### ISSUE TITLE
npm start results in TypeError [ERR_INVALID_FILE_URL_PATH]: File URL path must be absolute

### ISSUE THREAD

**Issue by lewi0622** [alexrudd2/saxi#139]
I'm trying to build and run using "npm start" on the latest code (as of July 7, 2024), but am getting the error "TypeError [ERR_INVALID_FILE_URL_PATH]: File URL path must be absolute". Any help would be appreciated!

System info:
node.js version v20.15.0
npm version 10.7.0
Windows 11 Version: 10.0.22631 Build 22631

Full console log:
```
PS C:\Users\lewi0\Desktop\alexrudd2\saxi> npm start          

> saxi@0.15.0 start
> npm run build && node cli.js


> saxi@0.15.0 prebuild
> npm run lint


> saxi@0.15.0 lint
> eslint --cache --ext .ts,.tsx src


> saxi@0.15.0 build
> npm run build:server && npm run build:ui


> saxi@0.15.0 build:server
> tsc


> saxi@0.15.0 build:ui
> node --experimental-modules build.mjs


  dist\ui\ui.js                              279.3kb
  dist\ui\ui.css                               5.5kb
  dist\ui\path-joining radius-IQOHHOQE.svg     479b
  dist\ui\point-joining radius-7FJFFNS3.svg    407b
  dist\ui\rotate-drawing-N3MHMTY3.svg          395b
  dist\ui\ui.js.map                          686.4kb
  dist\ui\ui.css.map                          12.1kb

Done in 89ms

  dist/ui/index.html - 286
  HTML Plugin Done in 75ms
node:internal/url:1433
    throw new ERR_INVALID_FILE_URL_PATH('must be absolute');
    ^

TypeError [ERR_INVALID_FILE_URL_PATH]: File URL path must be absolute
    at getPathFromURLWin32 (node:internal/url:1433:11)
    at fileURLToPath (node:internal/url:1464:35)
    at ./src/utils/defaults.js (C:\Users\lewi0\Desktop\alexrudd2\saxi\node_modules\svgdom\main-require.cjs:3986:125)
    at __webpack_require__ (C:\Users\lewi0\Desktop\alexrudd2\saxi\node_modules\svgdom\main-require.cjs:5278:41)
    at C:\Users\lewi0\Desktop\alexrudd2\saxi\node_modules\svgdom\main-require.cjs:5365:80
    at C:\Users\lewi0\Desktop\alexrudd2\saxi\node_modules\svgdom\main-require.cjs:5429:3
    at Object.<anonymous> (C:\Users\lewi0\Desktop\alexrudd2\saxi\node_modules\svgdom\main-require.cjs:5434:12)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32) {
  code: 'ERR_INVALID_FILE_URL_PATH'
}

Node.js v20.15.0
```

**Comment by alexrudd2** [comment]
I'm sorry this isn't working for you.  Unfortunately I cannot reproduce the issue on my Linux machine, nor on the Windows test runners.

This seems relevant: https://github.com/svgdotjs/svgdom/issues/111

Unfortunately the author of `svgdom` broke support for CommonJS, so I haven't been able to figure out how to upgrade to the latest version.  Perhaps you can try downgrading to `svgdom==0.1.15`?

**Comment by lewi0622** [comment]
Downgrading svgdom to 0.1.15 does indeed get things built and running. Thank you!
